### ISSUE TITLE
React does not recognize the `sortActive` prop on a DOM element.

### ISSUE THREAD

**Issue by Anandhu1991** [jbetancur/react-data-table-component#1160]
## Issue Check list
In console, gettting the following error in browser 
React does not recognize the `sortActive` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `sortactive` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

## To Reproduce
 Use Sort option in columns

## Expected behavior
No console errors

 
 

## Versions (please complete the following information)
 - React  18
 - Styled Components
 - OS: ubuntu
 - Browser  chrome

**Comment by Anandhu1991** [comment]
duplicate issue

**Comment by EdvinTr** [comment]
Any updates on this? 
The issue still persists for sortActive, minWidth and maxWidth even after #1154

**Comment by amirfaisalz** [comment]
any update on this?

**Comment by gergobalogh** [comment]
any news on this?

**Comment by jeppeliisberg** [comment]
I also have this issue after upgrading to react 18.

**Comment by SamuelDowse** [comment]
This is linked to the styled-components library, if you use styled-components version 5.x in your project, you won't get these errors, but if you use styled-components version 6.x and up you will see these errors.
Either drop your styled-components version in your project, or wait for react-data-table-component to upgrade to styled-components version 6.

**Comment by farizrifqi** [comment]
any update? I am using NextJS & Tailwind

**Comment by korlog** [comment]
Any progress on this problem? Will it be resolved soon?

**Comment by ADTC** [comment]
This happens because the peer dependency of this project is `"styled-components": ">= 4"` instead of `"styled-components": "^4.0.0"` or `"styled-components": "^5.0.0"`.

In my case it's not in `package.json` because it's a peer dependency. The `package-lock.json` already has version 6.x in it. However, running `npm i styled-components@^5.0.0` replaces the 6.x version with the latest 5.x version.

It adds a bunch of new stuff though. Hopefully the maintainer can upgrade support to 6.x. Is it even possible to use this project without `styled-components`? I don't really use it for anything myself.

**Comment by legarnica** [comment]
> This happens because the peer dependency of this project is `"styled-components": ">= 4"` instead of `"styled-components": "^4.0.0"` or `"styled-components": "^5.0.0"`.
> 
> In my case it's not in `package.json` because it's a peer dependency. The `package-lock.json` already has version 6.x in it. However, running `npm i styled-components@^5.0.0` replaces the 6.x version with the latest 5.x version.
> 
> It adds a bunch of new stuff though. Hopefully the maintainer can upgrade support to 6.x. Is it even possible to use this project without `styled-components`? I don't really use it for anything myself.

Thank You So Much. :)

**Comment by Lartaxx** [comment]
> This happens because the peer dependency of this project is `"styled-components": ">= 4"` instead of `"styled-components": "^4.0.0"` or `"styled-components": "^5.0.0"`.
> 
> In my case it's not in `package.json` because it's a peer dependency. The `package-lock.json` already has version 6.x in it. However, running `npm i styled-components@^5.0.0` replaces the 6.x version with the latest 5.x version.
> 
> It adds a bunch of new stuff though. Hopefully the maintainer can upgrade support to 6.x. Is it even possible to use this project without `styled-components`? I don't really use it for anything myself.

How did you find the problem?
I tried changing the dependency in my package-lock but it didn't change anything, I don't know how to fix it...

**Comment by ADTC** [comment]
> I tried changing the dependency in my package-lock

Did you run `npm i styled-components@^5.0.0`? Check your package-lock file for which version is installed, but don't edit the file directly.

Be sure to restart your local dev server.

**Comment by Lartaxx** [comment]
> > I tried changing the dependency in my package-lock
> 
> Did you run `npm i styled-components@^5.0.0`? Check your package-lock file for which version is installed, but don't edit the file directly.
> 
> Be sure to restart your local dev server.

Re, i have the version 6 `"styled-components": "^6.1.6"` in y package, and in my package-lock i have : 
```
"node_modules/react-data-table-component": {
            "version": "7.5.4",
            "resolved": "https://registry.npmjs.org/react-data-table-component/-/react-data-table-component-7.5.4.tgz",
            "integrity": "sha512-6DGVj3urJZfEEMuP652fSjxdRVKeyb+9d0YounVc+MX8jwoyXQW6KO10eyZqElE9QtVrKrCeJxR7vht9yxyJiw==",
            "dependencies": {
                "deepmerge": "^4.2.2"
            },
            "peerDependencies": {
                "react": ">= 16.8.3",
                "styled-components": ">= 4"
            }
        },
```

**Comment by ADTC** [comment]
Maybe you have another package that requires version 6 of styled components. That's a potential problem.

What's the result of you running `npm i styled-components@^5.0.0`?

**Comment by Lartaxx** [comment]
Oh it's good, thanks for your help ! 
Have a good day !

**Comment by mrwilbroad** [comment]
> `npm i styled-components@^5.0.0`

this solution work fine for my project , i realize styled-component v5.x is the solution for DOM error happened in console

**Comment by jbetancur** [comment]
This should be resolved in 7.6.2

**Comment by naviocean** [comment]
> This should be resolved in 7.6.2

It isn't resolved in 7.6.2

**Comment by JayBox325** [comment]
I am on:

```
"styled-components": "^6.1.13",
"react-data-table-component": "^7.6.2",
"react": "^18.3.1",
```

Still getting this error on `minWidth` and `maxWidth` props.

**Comment by JayBox325** [comment]
Still experiencing this issue.
